const useIdContent = {
  id: 'useId',
  title: 'useId Hook',
  icon: '🆔',
  theme: 'pink',
  tagline: 'Generate stable, unique IDs for accessibility attributes — safe for server rendering and hydration.',
  meta: 'Hooks · Modern',

  whatIsIt: {
    description: [
      'useId is a Hook that generates a unique, stable string ID on each call — designed specifically for linking elements via accessibility attributes like htmlFor/id, aria-describedby, or aria-labelledby.',
      'It exists to solve a subtle but real problem: IDs generated with simple counters or Math.random() can mismatch between server-rendered HTML and client-side hydration, producing console warnings and broken accessibility wiring. useId guarantees the same ID on both.'
    ],
    points: [
      'Syntax: const id = useId(); → returns a stable string like ":r1:" unique to that component instance.',
      'NOT meant for list keys — it generates one consistent ID per component instance, not a list of unique values for an array.',
      'Generates consistent IDs across server and client renders, eliminating hydration-mismatch warnings for accessibility wiring.'
    ],
    code: { title: 'The basic shape', snippet: `function PasswordField() {
  const id = useId();
  return (
    <>
      <label htmlFor={id}>Password</label>
      <input id={id} type="password" />
      <p id={\`\${id}-hint\`}>Must be at least 8 characters</p>
      {/* link the hint via aria-describedby using the SAME stable id */}
    </>
  );
}` },
    analogy: {
      icon: '🎫',
      title: 'Real-World Analogy',
      text: '"useId is like a hotel issuing a guest a room number at check-in that is guaranteed to match what\'s printed on both their key card AND the front-desk\'s records — generated by ONE authoritative system, not separately guessed by two different clerks (server vs. client) who might land on different numbers. That guaranteed match is exactly what links your <label> to your <input> reliably, everywhere."'
    }
  },

  whyUsed: {
    description: 'Form fields and other accessible widgets need matching id/htmlFor or aria-* attribute pairs to be usable by assistive technology (screen readers). Hand-rolling unique IDs (counters, random strings) is error-prone — duplicates across instances of a reusable component, and mismatches between server-rendered and client-hydrated output.',
    points: [
      'Guarantees uniqueness across multiple instances of the same reusable component on one page.',
      'Guarantees consistency between server-rendered HTML and the client\'s hydrated output — no hydration warnings.',
      'Removes the need to hand-manage ID counters, prefixes, or random-string generation for accessibility wiring.',
      'Lets you build genuinely reusable, accessible form components without the consumer needing to supply unique IDs themselves.'
    ]
  },

  whenToUse: {
    description: 'Reach for useId specifically — and only — when you need to generate IDs for linking accessibility attributes between elements within a component instance.',
    points: [
      'Connecting a <label> to its <input> via htmlFor/id, especially inside reusable form-field components.',
      'Linking descriptive or error text to a control via aria-describedby or aria-errormessage.',
      'Associating a heading with a region via aria-labelledby (e.g. a custom dialog or accordion panel).',
      'Any scenario needing a guaranteed-unique, guaranteed-stable identifier string tied to a specific component instance.'
    ],
    analogy: {
      icon: '🚫',
      title: 'When NOT to use useId',
      text: '"Never use useId to generate keys for items in a list (<li key={useId()}>) — Hooks can\'t be called inside loops, and more fundamentally, list keys should be derived from the DATA itself (a stable id field) so React can track items across reorders/insertions/deletions. useId solves a completely different problem: linking accessibility attributes WITHIN a single component instance."'
    }
  },

  howItWorks: {
    description: 'useId derives its value from the position of the component within the React tree, using a shared counter/path mechanism that produces the exact same sequence on both the server (during server-side rendering) and the client (during hydration) — as long as the tree structure matches, which React requires for successful hydration anyway.',
    code: {
      title: 'A reusable, accessible form-field component',
      snippet: `function FormField({ label, hint, ...inputProps }) {
  const id = useId();
  const hintId = \`\${id}-hint\`;

  return (
    <div className="form-field">
      <label htmlFor={id}>{label}</label>
      <input id={id} aria-describedby={hint ? hintId : undefined} {...inputProps} />
      {hint && <p id={hintId} className="hint">{hint}</p>}
    </div>
  );
}

// Render this THREE times on one page — each instance gets its own
// guaranteed-unique id, with zero chance of collision or hydration mismatch:
<FormField label="Email" hint="We'll never share it" type="email" />
<FormField label="Username" hint="Letters and numbers only" />
<FormField label="Bio" hint="Max 160 characters" />`
    },
    points: [
      'You can derive multiple related IDs from a single useId() call by appending suffixes — id, `${id}-hint`, `${id}-error` — keeping them all guaranteed-unique together.',
      'If you need consistent prefixes across an entire app (e.g. for CSS scoping in a design system), React supports an `identifierPrefix` option on the root render APIs.',
      'Calling useId multiple times in the same component returns a different ID each time — call it once per logical "group" of related IDs and derive variants by suffixing.'
    ]
  },

  flowDiagram: {
    title: 'Why useId avoids hydration mismatches',
    steps: [
      { icon: '🖥️', label: 'Server renders <FormField>', note: 'useId() → ":r0:" (tree-position based)' },
      { icon: '📦', label: 'HTML sent to browser', note: 'id=":r0:" baked into markup' },
      { icon: '💧', label: 'Client hydrates same tree', note: 'useId() computes ":r0:" again — IDENTICAL' },
      { icon: '✅', label: 'No mismatch warning', note: 'Accessibility wiring works from the first paint' }
    ]
  },

  realWorldExamples: {
    intro: 'useId is the quiet glue behind accessible, reusable component libraries:',
    items: [
      { icon: '📝', title: 'Reusable form-field components', description: 'A design system\'s <TextField label="..."> wires its own <label htmlFor> / <input id> pair internally — consumers never have to think about, supply, or risk colliding on IDs.' },
      { icon: '⚠️', title: 'Linking error/hint text via aria-describedby', description: 'A validated input announces its error message to screen readers by referencing a derived id (`${id}-error`) — generated safely whether rendered once or fifty times on a page.' },
      { icon: '🗂️', title: 'Accordion / tabs / dialog accessibility wiring', description: 'Custom interactive components connect headers to panels via aria-labelledby/aria-controls using guaranteed-unique, guaranteed-matching IDs across server and client renders.' },
      { icon: '🧩', title: 'Component libraries shipped to other teams', description: 'Any component that must work correctly when rendered multiple times on the same page — without consumers manually passing unique id props — relies on useId internally.' }
    ]
  },

  prosAndCons: {
    pros: [
      'Eliminates hydration-mismatch warnings for accessibility-related IDs in server-rendered apps.',
      'Guarantees uniqueness across multiple instances of the same component automatically — no manual bookkeeping.',
      'Makes genuinely reusable, accessible components possible without burdening consumers with unique-id props.',
      'Trivial to derive multiple related, guaranteed-matching IDs by suffixing a single base id.'
    ],
    cons: [
      'Solves a narrow, specific problem — easy to reach for in the wrong context (e.g. list keys) if its purpose is misunderstood.',
      'The generated strings are intentionally opaque (e.g. ":r1:") — not meant to be human-readable or stable across app versions/renders order changes.',
      'Adds a small amount of indirection compared to simply hardcoding an id string in a one-off, non-reusable component.',
      'Only relevant where accessibility attribute linkage is needed — irrelevant to the vast majority of everyday components.'
    ]
  },

  comparison: {
    title: 'useId vs. hand-rolled IDs vs. list keys — three different problems',
    left: {
      title: '❌ Hand-rolled IDs — fragile',
      tone: 'bad',
      code: `let counter = 0;
function FormField() {
  const id = \`field-\${counter++}\`; // ❌ mismatches between
  return <input id={id} />;          //    server render and client hydration!
}`,
      note: 'Module-level counters reset differently on server vs. client, and collide across multiple page renders — a classic source of hydration warnings.'
    },
    right: {
      title: '✅ useId — stable & matched',
      tone: 'good',
      code: `function FormField() {
  const id = useId(); // ✅ identical on server AND client,
  return <input id={id} />; //    unique per instance, zero bookkeeping
}

// (Separately: list keys should come from DATA, e.g. item.id — never useId)`,
      note: 'Tree-position-based generation guarantees the server and client compute the exact same value — and remains distinct from the unrelated "list key" problem.'
    }
  },

  commonMistakes: {
    items: [
      {
        title: 'Using useId to generate list keys',
        wrong: `{items.map(item => (\n  <li key={useId()}>{item.name}</li> // ❌ Hooks can't be called in loops — and keys must come from data\n))}`,
        right: `{items.map(item => (\n  <li key={item.id}>{item.name}</li> // ✅ stable, data-derived key — lets React track items across reorders\n))}`,
        note: 'These solve different problems entirely: useId generates ONE stable id for accessibility wiring within an instance; list keys must be derived from the data itself so React can correctly track identity across insertions, deletions, and reorders. Also — Hooks can never be called inside loops.'
      },
      {
        title: 'Calling useId once and reusing the raw value for unrelated elements',
        wrong: `const id = useId();\n<label htmlFor={id}>Name</label><input id={id} />\n<label htmlFor={id}>Email</label><input id={id} /> {/* ❌ duplicate ids on the page! */}`,
        right: `const nameId = useId();\nconst emailId = useId();\n<label htmlFor={nameId}>Name</label><input id={nameId} />\n<label htmlFor={emailId}>Email</label><input id={emailId} /> {/* ✅ each pair gets its own id */}`,
        note: 'Each logical group of related elements (one label+input pair, one input+hint+error trio) needs its own useId() call (or its own derived suffix from one call) — reusing a single raw id across unrelated element groups recreates the duplicate-id problem useId exists to prevent.'
      },
      {
        title: 'Treating the generated string as meaningful or stable across versions',
        note: 'The exact format of useId\'s output (e.g. ":r1:") is an implementation detail that can change between React versions — never parse it, store it, or rely on its specific shape. Treat it purely as an opaque, unique string for attribute linkage.'
      }
    ]
  },

  bestPractices: [
    'Reserve useId strictly for accessibility-attribute linkage (htmlFor/id, aria-describedby, aria-labelledby) — never for list keys or general-purpose unique values.',
    'Call it once per logical group of related elements, and derive any additional related IDs by suffixing (`${id}-hint`, `${id}-error`).',
    'Bake it into reusable component internals so consumers never need to think about, generate, or risk colliding on IDs themselves.',
    'Treat the returned string as opaque — never parse it, persist it, or assume anything about its format.',
    'If building a design system that needs app-wide ID prefixing (e.g. to scope styles), look into the `identifierPrefix` option on the root rendering APIs rather than hand-rolling prefixes.'
  ],

  interviewQuestions: [
    { q: 'What problem does useId solve, and why can\'t you just use a counter or Math.random()?', a: 'It generates unique, stable ID strings for linking accessibility attributes (label/input pairs, aria-describedby targets) — guaranteed to match between server-rendered HTML and client-side hydration. A module-level counter or Math.random() can produce DIFFERENT values on the server vs. the client (different execution order, different starting states), causing hydration-mismatch warnings and broken id/htmlFor or aria-* linkage on first paint. useId derives its value from the component\'s position in the tree, which is identical on both sides.' },
    { q: 'Why shouldn\'t useId be used to generate keys for a list of rendered items?', a: 'Two reasons: practically, Hooks cannot be called inside loops/conditionals (the Rules of Hooks), so calling useId() per list item is invalid. Conceptually, list keys need to be stable identifiers tied to the underlying DATA (e.g. item.id) so React can correctly track each item\'s identity across reorders, insertions, and deletions — useId generates an identifier tied to a component\'s position in the tree, which is an entirely different (and unrelated) kind of stability guarantee.' },
    { q: 'How would you use useId to connect a label, an input, and a hint/error message accessibly?', a: 'Call useId() once to get a base id, then derive related IDs by suffixing it: `const id = useId(); const hintId = `${id}-hint`;`. Use `id` for both <label htmlFor={id}> and <input id={id}>, and `hintId` for both the hint <p id={hintId}> and the input\'s aria-describedby={hintId}. This guarantees all the related elements stay correctly linked together and remain unique even if the component is rendered many times on the same page.' },
    { q: 'Why is useId considered safe for server-side rendering while a simple incrementing counter is not?', a: 'useId derives its output from the component\'s position within the React tree — a structural property that is identical whether the tree is being rendered on the server or hydrated on the client (assuming the structures match, which React requires for successful hydration anyway). A plain incrementing counter, by contrast, depends on RUNTIME EXECUTION ORDER, which can differ between the server\'s render pass and the client\'s hydration pass — producing different numbers and a server/client HTML mismatch.' },
    { q: 'Should you treat the string returned by useId as meaningful or parse it in any way?', a: 'No — it should be treated as a completely opaque, unique string. Its exact format (e.g. ":r1:") is an internal implementation detail that can change between React versions; the only guarantees useId makes are uniqueness (within the rendered tree) and stability (matching between server and client renders of the same tree) — not any particular shape, readability, or persistence guarantee.' }
  ],

  summary: {
    description: 'useId generates unique, tree-position-derived ID strings purpose-built for linking accessibility attributes — guaranteed to match between server-rendered HTML and client hydration, and guaranteed unique across multiple instances of the same component. Use it strictly for label/input pairs and aria-* linkage (never for list keys), derive related IDs by suffixing a single base call, and let it quietly make your reusable components properly accessible with zero consumer-side bookkeeping.'
  },

  furtherReading: [
    { label: 'Official docs', note: 'react.dev/reference/react/useId — the canonical reference, including the "Generating IDs for several related elements" and "Specifying a shared prefix for all generated IDs" sections.' },
    { label: 'Related topic', note: 'See "Forms" for the broader accessibility patterns (labels, error messaging) that useId is most commonly used to wire up.' }
  ]
};

export default useIdContent;
