const useIdContent = {
  id: 'useId',
  title: 'useId Hook',
  icon: '🆔',
  theme: 'pink',
  tagline: 'useId generates a unique, stable ID for linking accessibility attributes like htmlFor and aria-describedby.',
  meta: 'Hooks · Modern',

  whatIsIt: {
    description: [
      'useId generates a unique, stable string ID tied to each component instance — designed specifically for linking elements via accessibility attributes like htmlFor/id and aria-describedby.',
      'It solves a subtle problem: IDs generated with counters or Math.random() can mismatch between server-rendered HTML and client hydration. useId guarantees the same ID on both.'
    ],
    points: [
      'Syntax: const id = useId(); — returns a stable string like ":r1:".',
      'NOT for list keys — it generates one ID per component instance, not a list of unique values.',
      'Guarantees matching IDs between server render and client hydration.'
    ],
    code: { title: 'The basic shape', snippet: `function PasswordField() {
  const id = useId();
  return (
    <>
      <label htmlFor={id}>Password</label>
      <input id={id} type="password" />
      <p id={\`\${id}-hint\`}>Must be at least 8 characters</p>
      {/* link the hint via aria-describedby using the SAME stable id */}
    </>
  );
}` },
    analogy: {
      icon: '🎫',
      title: 'Real-World Analogy',
      text: '"useId is like a hotel that issues a guest a room number at check-in, guaranteed to match both the key card and the front desk records — generated by ONE authoritative system, not separately guessed by two different clerks (server vs. client) who might pick different numbers."'
    }
  },

  whyUsed: {
    description: 'Form fields and accessible widgets need matching id/htmlFor or aria-* attribute pairs for screen readers to work. Hand-rolling IDs is error-prone — duplicates across instances and mismatches between server and client.',
    points: [
      'Guarantees uniqueness across multiple instances of the same component.',
      'Guarantees consistency between server-rendered HTML and client hydration.',
      'Removes the need to hand-manage ID counters or random strings.',
      'Lets you build reusable, accessible form components without consumers supplying IDs.'
    ]
  },

  whenToUse: {
    description: 'Use useId only when you need to generate IDs for linking accessibility attributes between elements within a component instance.',
    points: [
      'Connecting a <label> to its <input> via htmlFor/id.',
      'Linking descriptive or error text via aria-describedby or aria-errormessage.',
      'Associating a heading with a region via aria-labelledby.',
      'Any scenario needing a unique, stable identifier tied to a component instance.'
    ],
    analogy: {
      icon: '🚫',
      title: 'When NOT to use useId',
      text: '"Never use useId to generate list keys — Hooks cannot be called inside loops, and list keys must come from the DATA itself so React can track items across reorders. useId solves accessibility wiring within a single component instance, not list identity."'
    }
  },

  howItWorks: {
    description: 'useId derives its value from the component\'s position in the React tree — a structural property that is identical on the server and the client, producing the same ID on both sides.',
    code: {
      title: 'A reusable, accessible form-field component',
      snippet: `function FormField({ label, hint, ...inputProps }) {
  const id = useId();
  const hintId = \`\${id}-hint\`;

  return (
    <div className="form-field">
      <label htmlFor={id}>{label}</label>
      <input id={id} aria-describedby={hint ? hintId : undefined} {...inputProps} />
      {hint && <p id={hintId} className="hint">{hint}</p>}
    </div>
  );
}

// Render this THREE times on one page — each instance gets its own
// guaranteed-unique id, with zero chance of collision or hydration mismatch:
<FormField label="Email" hint="We'll never share it" type="email" />
<FormField label="Username" hint="Letters and numbers only" />
<FormField label="Bio" hint="Max 160 characters" />` },
    points: [
      // eslint-disable-next-line no-template-curly-in-string
      'Derive multiple related IDs from one useId() call by appending suffixes: `${id}-hint`, `${id}-error`.',
      'Calling useId multiple times in the same component returns a different ID each time.',
      'React supports an `identifierPrefix` option on root APIs for app-wide ID prefixing.'
    ]
  },

  flowDiagram: {
    title: 'Why useId avoids hydration mismatches',
    steps: [
      { icon: '🖥️', label: 'Server renders <FormField>', note: 'useId() → ":r0:" (tree-position based)' },
      { icon: '📦', label: 'HTML sent to browser', note: 'id=":r0:" baked into markup' },
      { icon: '💧', label: 'Client hydrates same tree', note: 'useId() computes ":r0:" again — IDENTICAL' },
      { icon: '✅', label: 'No mismatch warning', note: 'Accessibility wiring works from the first paint' }
    ]
  },

  realWorldExamples: {
    intro: 'useId is the quiet glue behind accessible, reusable component libraries:',
    items: [
      { icon: '📝', title: 'Reusable form-field components', description: 'A design system\'s <TextField> wires its own label/input pair internally — consumers never need to supply or worry about colliding IDs.' },
      { icon: '⚠️', title: 'Linking error text via aria-describedby', description: 'A validated input announces its error message to screen readers by referencing a derived id — safe whether rendered once or fifty times.' },
      { icon: '🗂️', title: 'Accordion and dialog accessibility wiring', description: 'Custom interactive components connect headers to panels via aria-labelledby with guaranteed-unique, guaranteed-matching IDs.' },
      { icon: '🧩', title: 'Component libraries for other teams', description: 'Any component that must work correctly when rendered multiple times on the same page relies on useId internally.' }
    ]
  },

  prosAndCons: {
    pros: [
      'Eliminates hydration-mismatch warnings for accessibility IDs in server-rendered apps.',
      'Guarantees uniqueness across multiple instances automatically — no manual bookkeeping.',
      'Makes reusable, accessible components possible without burdening consumers.',
      'Trivial to derive multiple related IDs by suffixing a single base id.'
    ],
    cons: [
      'Solves a narrow, specific problem — easy to misuse in the wrong context.',
      'Generated strings are intentionally opaque — not human-readable or stable across versions.',
      'Adds a small amount of indirection compared to a hardcoded id in a one-off component.',
      'Only relevant where accessibility attribute linkage is needed.'
    ]
  },

  comparison: {
    title: 'useId vs. hand-rolled IDs vs. list keys',
    left: {
      title: '❌ Hand-rolled IDs — fragile',
      tone: 'bad',
      code: `let counter = 0;
function FormField() {
  const id = \`field-\${counter++}\`; // ❌ mismatches between
  return <input id={id} />;          //    server render and client hydration!
}`,
      note: 'Module-level counters reset differently on server vs. client and collide across multiple renders.'
    },
    right: {
      title: '✅ useId — stable & matched',
      tone: 'good',
      code: `function FormField() {
  const id = useId(); // ✅ identical on server AND client,
  return <input id={id} />; //    unique per instance, zero bookkeeping
}

// (Separately: list keys should come from DATA, e.g. item.id — never useId)`,
      note: 'Tree-position-based generation guarantees the server and client compute the exact same value.'
    }
  },

  commonMistakes: {
    items: [
      {
        title: 'Using useId to generate list keys',
        wrong: `{items.map(item => (\n  <li key={useId()}>{item.name}</li> // ❌ Hooks can't be called in loops\n))}`,
        right: `{items.map(item => (\n  <li key={item.id}>{item.name}</li> // ✅ stable, data-derived key\n))}`,
        note: 'useId generates one ID for accessibility wiring within an instance. List keys must come from the data so React can track items across reorders. Also, Hooks cannot be called inside loops.'
      },
      {
        title: 'Reusing one raw id for unrelated elements',
        wrong: `const id = useId();\n<label htmlFor={id}>Name</label><input id={id} />\n<label htmlFor={id}>Email</label><input id={id} /> {/* ❌ duplicate ids! */}`,
        right: `const nameId = useId();\nconst emailId = useId();\n<label htmlFor={nameId}>Name</label><input id={nameId} />\n<label htmlFor={emailId}>Email</label><input id={emailId} /> {/* ✅ */}`,
        note: 'Each logical group of related elements needs its own useId() call or its own suffix. Reusing one raw id for unrelated groups recreates the duplicate-id problem.'
      },
      {
        title: 'Treating the generated string as meaningful',
        note: 'The exact format of the output (like ":r1:") is an implementation detail that can change between React versions. Treat it as an opaque, unique string — never parse it or store it.'
      }
    ]
  },

  bestPractices: [
    'Reserve useId strictly for accessibility attribute linkage — never for list keys.',
    // eslint-disable-next-line no-template-curly-in-string
    'Call it once per logical group and derive additional IDs by suffixing: `${id}-hint`, `${id}-error`.',
    'Bake it into reusable component internals so consumers never think about IDs.',
    'Treat the returned string as opaque — never parse it or make assumptions about its format.',
    'For app-wide ID prefixing in a design system, use the identifierPrefix option on root render APIs.'
  ],

  interviewQuestions: [
    { q: 'What problem does useId solve, and why can\'t you just use a counter or Math.random()?', a: 'It generates unique, stable IDs for accessibility attributes — guaranteed to match between server-rendered HTML and client hydration. A counter or Math.random() can produce DIFFERENT values on the server vs. the client, causing hydration-mismatch warnings and broken aria-* linkage. useId derives its value from the component\'s tree position, which is identical on both sides.' },
    { q: 'Why should useId not be used to generate list keys?', a: 'Hooks cannot be called inside loops, so using useId per list item is invalid. Also, list keys need to be stable identifiers tied to the DATA so React can track each item across reorders — useId generates an identifier tied to tree position, which is a completely different kind of stability.' },
    // eslint-disable-next-line no-template-curly-in-string
    { q: 'How do you use useId to connect a label, input, and hint accessibly?', a: 'Call useId() once to get a base id, then derive related IDs by suffixing: const hintId = `${id}-hint`. Use id for both <label htmlFor={id}> and <input id={id}>, and hintId for the hint <p id={hintId}> and the input\'s aria-describedby={hintId}. All related elements stay correctly linked even if the component is rendered many times.' },
    { q: 'Why is useId considered safe for server-side rendering while a simple counter is not?', a: 'useId derives its output from the component\'s position in the React tree — identical whether rendered on the server or hydrated on the client. A plain counter depends on runtime execution order, which can differ between the server and client render passes, producing different numbers and a hydration mismatch.' },
    { q: 'Should you treat the string returned by useId as meaningful?', a: 'No — treat it as a completely opaque, unique string. Its exact format is an internal implementation detail that can change between React versions. The only guarantees are uniqueness within the tree and stability between server and client renders.' }
  ],

  summary: {
    description: 'useId generates unique, tree-position-derived IDs for linking accessibility attributes — guaranteed to match between server and client renders and unique across multiple instances of the same component. Use it strictly for label/input pairs and aria-* linkage, never for list keys.'
  },

  furtherReading: [
    { label: 'Official docs', note: 'react.dev/reference/react/useId — the canonical reference including generating multiple related IDs and the identifierPrefix option.' },
    { label: 'Related topic', note: 'See "Forms" for the broader accessibility patterns that useId is most commonly used to wire up.' }
  ]
};

export default useIdContent;
